// <auto-generated />
using System;
using AirsoftWebStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirsoftWebStore.Data.Migrations
{
    [DbContext(typeof(AirsoftStoreDbContext))]
    [Migration("20230811193440_AddingMoreEntitiesToTheConfigurations")]
    partial class AddingMoreEntitiesToTheConfigurations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirsoftWebStore.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Test");

                    b.Property<bool>("HasGunsmithRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Test");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e445865-a24d-4543-a6c6-9443d048cdb9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7dfb3c69-c935-43df-a27b-668afb091f5a",
                            Email = "admin@soldier.eu",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            HasGunsmithRequest = false,
                            LastName = "Adminov",
                            LockoutEnabled = true,
                            Money = 0m,
                            NormalizedEmail = "ADMIN@SOLDIER.EU",
                            NormalizedUserName = "ADMIN@SOLDIER.EU",
                            PasswordHash = "AQAAAAEAACcQAAAAEF78kWFknigxhjR5fhkU480/22khPVlEuJ/l5L4uJZp6TiwBUmbTSaeAbzt2OwBpZg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1BC726483DA146C7AB96961EBD8FA88B",
                            TwoFactorEnabled = false,
                            UserName = "admin@soldier.eu"
                        });
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsumativeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ConsumativeId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("GunId");

                    b.HasIndex("PartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rifle"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pistol"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Submachine gun"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sniper rifle"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shotgun"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Grenade launcher"
                        });
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Consumative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consumatives");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d376cfd-d367-4401-8f2b-b3367c098ef9"),
                            Description = "For high precision and really good shots. These BBs are going to like you a lot! They are competition grade and are really balanced.",
                            ImageUrl = "https://m.media-amazon.com/images/I/51QY6Y7klQL._AC_UF1000,1000_QL80_.jpg",
                            IsActive = false,
                            Name = "BBs",
                            Price = 15.55m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("5a4f16f5-5183-4dc6-939f-92258369f495"),
                            Description = "Flashbang grenade replica. The body is made of plastic, the spoon, the pin and the spring in the dummy fuse are made of steel.",
                            ImageUrl = "https://static5.gunfire.com/eng_pm_Flashbang-grenade-dummy-1152234183_1.webp",
                            IsActive = false,
                            Name = "Flashbang grenade dummy",
                            Price = 11.50m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("63cc50ff-66c3-49d1-9e40-7ecd0dbafd08"),
                            Description = "The grenade’s diameter is 40mm and  it is made of metal. The green gas grenade is designed to be used with the grenade launcher having the inner diameter of 40mm. The grenade is powered by green-gas. It holds 84 BB pellets.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_40mm-green-gas-grenade-84-BB-pellets-SHS-1152200858_1.webp",
                            IsActive = false,
                            Name = "40mm green-gas grenade",
                            Price = 38.50m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("0c83291a-e1c7-4639-90b1-74d6560afaee"),
                            Description = "Flashbang grenade launcher with loader made of plastic.",
                            ImageUrl = "https://static1.gunfire.com/eng_pm_Flashbang-grenade-dummy-with-loader-Tan-1152234185_1.webp",
                            IsActive = false,
                            Name = "Flashbang grenade dummy with loader - Tan",
                            Price = 12.76m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("9aa8283e-1014-485f-9e6b-2324cd204284"),
                            Description = "A solid gas powered grenade by Action Sport Games, which will be perfect for in-door games  for dispatching larger groups of opponents.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_Storm-360-Gen-3-Green-Gas-Grenade-lime-green-1152230228_1.webp",
                            IsActive = false,
                            Name = "Storm 360 Gen.3 Green Gas Grenade - lime green",
                            Price = 51.55m,
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1938aaa9-aa2f-4f04-a6f8-e91a65b6ee26"),
                            Description = "The first aid kit can be attached using a Velcro panel to the equipment compatible with the MOLLE system or directly to the Velcro straps. The first aid kit also includes a tape with a buckle that will also help compress the contents of the pouch.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_Large-tear-off-first-aid-kit-Black-1152235193_1.webp",
                            IsActive = false,
                            Name = "Large tear - off first aid kit",
                            Price = 10.75m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("c3e3661b-610b-401e-bbc3-b861954fc6d4"),
                            Description = "Uniform clothing in the original and unique Multi-environmental Adaptive Pattern camouflage, intended for civilian and professional users who are interested in the military and actively spend their time outdoors - as well as in difficult and extreme conditions.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_CJP-02-Pro-Combat-Jacket-MAPA-R-1152234971_1.webp",
                            IsActive = false,
                            Name = "CJP-02 Pro Combat Jacket",
                            Price = 149.50m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("1e7fee53-65d8-46ee-a075-ede3e1a2825a"),
                            Description = "The light protective helmet LHO-01 is the first bulletproof high cut helmet produced by MASKPOL designed for the civilian market. It is designed to protect the wearer's head against direct shrapnel wounds and certain small arms projectiles.",
                            ImageUrl = "https://static4.gunfire.com/eng_pm_Ballistic-helmet-LHO-01-Olive-1152235163_1.webp",
                            IsActive = false,
                            Name = "Ballistic helmet LHO-01",
                            Price = 472.82m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("c0fe3f57-4d4a-427b-ad95-c5ea795549a8"),
                            Description = "Advanced active headset powered by a built-in battery.",
                            ImageUrl = "https://static5.gunfire.com/eng_pm_Tactical-HD-16-Bluetooth-Active-Headset-Olive-1152234035_1.webp",
                            IsActive = false,
                            Name = "Tactical HD-16 Bluetooth Active Headset",
                            Price = 123.50m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("6ac2fbb9-2d8f-49c5-8ae8-2bb39ad1e7d1"),
                            Description = "The Bowman Elite II headset. The elastic head strap guarantees a proper placement of the headset on the head.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_Bowman-Elite-II-headset-FG-1152195615_1.webp",
                            IsActive = false,
                            Name = "Bowman Elite II headset",
                            Price = 18.30m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("dd2f87a1-5246-4b7e-b27e-2a92f64729a4"),
                            Description = "The ERM Headset is made out of durable plastic and metal. The ear pads and the headband padding have been equipped with covers to ensure high user comfort.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_Tactical-headset-ERM-Black-1152234028_1.webp",
                            IsActive = false,
                            Name = "Tactical headset ERM",
                            Price = 60.45m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("5bb85faa-2c1e-4c8e-8faa-195d05f8fa91"),
                            Description = "A Plate Carrier tactical vest made of durable nylon by GFC Tactical. The vest is adapted to carrying a set of ballistic inserts and its compatibility with MOLLE / PALS load-bearing system enables the attachment and any configuration of additional pouches, pockets or bags.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_Quick-Release-Plate-Carrier-Tactical-Vest-Tan-1152228378_1.webp",
                            IsActive = false,
                            Name = "Quick Release Plate Carrier Tactical Vest",
                            Price = 74.80m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("9f73713a-91c0-4913-b9f4-604cdd0f592b"),
                            Description = "A panel by Viper Tactical made of durable nylon. The panel is dedicated for tactical vests in Buckle Up system and attachable using a hook and loop fastener and snap buckles.",
                            ImageUrl = "https://static5.gunfire.com/eng_pm_VX-Buckle-Up-Mag-Rig-Panel-Coyote-Brown-1152227952_1.webp",
                            IsActive = false,
                            Name = "VX Buckle Up Mag Rig Panel",
                            Price = 40.70m,
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Gun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Guns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ff8f5f3-a312-45c2-8dcd-708179a2b47c"),
                            CategoryId = 1,
                            Description = "Specna Arms proudly presents the FLEX line of replicas. An affordable price combined with an innovative quick spring change system, great performance straight out of the box and high-quality components makes this series an excellent choice for both beginners and experienced airsoft players alike.",
                            ImageUrl = "https://www.zerooneairsoft.com/products_image_15055_0.jpg",
                            IsActive = false,
                            Manufacturer = "Specna Arms",
                            Name = "SA-F02 FLEX HT",
                            Price = 250m,
                            Quantity = 3,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("246a87a9-6996-45ec-9b18-e3cb7d5d8b62"),
                            CategoryId = 2,
                            Description = "Double Bell brand airsoft replica powered by green gas. The grip facings are made of plastic. The breech drop lever and decocker are made of steel. The skeleton, lock, external barrel and the rest of the components are made of aluminium and zinc alloy.",
                            ImageUrl = "https://static4.gunfire.com/eng_pm_P226-pistol-replica-778-Tan-1152235155_1.webp",
                            IsActive = false,
                            Manufacturer = "Dobuel Bell",
                            Name = "P226",
                            Price = 90m,
                            Quantity = 6,
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("6792fc5d-c0c5-4d47-835a-57ec7c3d57de"),
                            CategoryId = 4,
                            Description = "This sniper rifle will win make you feel like a real soldier. With its silence and long range, you will be able to make really good shots and the enemies will wonder what had happened to them after.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_TAC-41-A-airsoft-sniper-rifle-Wolf-Grey-1152234909_1.webp",
                            IsActive = false,
                            Manufacturer = "Silverback Airsoft",
                            Name = "TAC-41 A",
                            Price = 710.50m,
                            Quantity = 3,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("5f050acd-acb9-4567-bc0d-1c9f55584f30"),
                            CategoryId = 5,
                            Description = "GF Custom Division is an idea conceived in the heads of the Gunfire airsoft team. We offer you the highest quality replicas, modified and configured by us, using only the best, tried and tested parts and accessories. Each element serves a specific purpose - these are exactly the configurations that we would like to use in the playing field ourselves. Many years of airsoft experience helps us in working on custom airsoft guns like this one, so we can safely say that GF Custom Division is a project created 100% by players for players.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_8871-Shotgun-Replica-Corpo-Wars-WGTO-1152234920_1.webp",
                            IsActive = false,
                            Manufacturer = "GF Custom Division",
                            Name = "8871",
                            Price = 260.57m,
                            Quantity = 5,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("30ae4845-9dca-4c13-9e03-2122f285ce45"),
                            CategoryId = 1,
                            Description = "The EDGE 2.0 ™ series introduces a completely new quality to the Specna Arms replica family, adding new functionalities and innovations to the tried and tested design. As a result, Specna Arms EDGE 2.0 ™ carbines offer an exceptional high level of craftsmanship and technical advancement straight out of the box.",
                            ImageUrl = "https://static5.gunfire.com/eng_pm_SA-H22-EDGE-2-0-TM-Carbine-Replica-black-1152225956_1.webp",
                            IsActive = false,
                            Manufacturer = "Specna Arms",
                            Name = "SA-H22",
                            Price = 385.25m,
                            Quantity = 4,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("bbd23e2b-78db-424e-abdf-998c1ab2620f"),
                            CategoryId = 1,
                            Description = "Specna Arms meets the expectations of clients by presenting the CORE™ line of products - an exceptional series of replicas that introduces a new quality to the market. Attractive price in combination with an innovative spring exchange system as well as high-quality materials make this replica suitable for beginners and seasoned airsoft players alike.",
                            ImageUrl = "https://static5.gunfire.com/eng_pm_SA-C10-PDW-CORE-TM-Carbine-Replica-Black-1152225067_1.webp",
                            IsActive = false,
                            Manufacturer = "Specna Arms",
                            Name = "SA-C10 PDW CORE",
                            Price = 165.50m,
                            Quantity = 7,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("3c9f51a9-aa6c-4920-a0f8-e902786e4bdc"),
                            CategoryId = 1,
                            Description = "Specna Arms meets the expectations of clients by presenting the CORE™ line of products - an exceptional series of replicas that introduces a new quality to the market. An attractive price in combination with an innovative spring change system as well as high-quality materials make this replica suitable for beginners and seasoned airsoft players alike.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_SA-C05-CORE-TM-Carbine-Replica-1152215724_1.webp",
                            IsActive = false,
                            Manufacturer = "Specna Arms",
                            Name = "SA-C05 CORE",
                            Price = 165.40m,
                            Quantity = 4,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("326bada2-2d00-4134-bcb4-5e9f30da9f18"),
                            CategoryId = 1,
                            Description = "The receiver, stock slide and an SF stock that holds the battery as well as the pistol grip were made of nylon fiber reinforced polymer. Remaining components such as the barrel, handguard, flash hider, enlarged charging handle and tactical sling swivels were made of metal (parts made of steel include the screws, pins, shell ejection window and mock bolt carrier). The receiver bears markings and a serial number.",
                            ImageUrl = "https://static4.gunfire.com/eng_pm_SA-C22-CORE-TM-Carbine-Replica-Chaos-Bronze-1152231391_1.webp",
                            IsActive = false,
                            Manufacturer = "Specna Arms",
                            Name = "SA-C22 CORE",
                            Price = 180.23m,
                            Quantity = 6,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("a7f0eed2-c4aa-44e3-a4f1-4628c222e529"),
                            CategoryId = 1,
                            Description = "The replica’s parts are very well aligned - in a way that could be thus far noticed solely in replicas by such top-tier manufacturers as G&P or Classic Army, the replica is also perfectly balanced. This allows for an almost ideal maneuverability of the replica and its weight is almost unnoticeable once the replica has been shouldered.",
                            ImageUrl = "https://static1.gunfire.com/eng_pm_SA-H11-ONE-TM-Carbine-Replica-Black-1152227616_1.webp",
                            IsActive = false,
                            Manufacturer = "Specna Arms",
                            Name = "SA-H11 ONE",
                            Price = 303.54m,
                            Quantity = 8,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("60cbe3c8-b462-4772-97e1-30a36326568c"),
                            CategoryId = 4,
                            Description = "A spring action replica of a sniper rifle. It is a bolt-action replica, which means that it has to be reloaded after each shot. The cradle with the stock were made from a durable polymer. Metal was used in the manufacture process of such elements as the barrel, trigger guard, bolt carrier, magwell and the charging handle.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_SW-04-Sniper-Rifle-Replica-with-Scope-and-Bipod-Olive-Drab-1152194766_1.webp",
                            IsActive = false,
                            Manufacturer = "Snow Wolf",
                            Name = "SW-04",
                            Price = 172.42m,
                            Quantity = 5,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("7d2179ce-d198-4a73-a210-f37fc00ee43b"),
                            CategoryId = 4,
                            Description = "SMC-9 is a first construction of this type by G&G on the market. It is a combination of a submachine gun and a GTP9 pistol that came together into a unique construction. Thanks to its size, it is ideal for CQB games. Parts taken from GTP9 replica include the frame and the trigger mechanism - the barrel, chamber, cylinder set all belong to the conversion. Thanks to a special mechanism, the replica can fire in semi-auto as well as full-auto modes.",
                            ImageUrl = "https://static5.gunfire.com/eng_pm_SMC-9-Submachine-Gun-Replica-Black-1152226182_1.webp",
                            IsActive = false,
                            Manufacturer = "G&G Armament",
                            Name = "SMC-9",
                            Price = 440.25m,
                            Quantity = 7,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("86951de2-06d3-45ff-99c6-09d7882c3fe1"),
                            CategoryId = 6,
                            Description = "The grenade launcher replica is made of durable plastic and metal. The elements such as the barrel, the front iron aiming sights and the RIS rails are made of metal. The replica’s stock, the pistol grip, the body and the rear iron aiming sight are made of durable plastic.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_GL-06-grenade-launcher-1152195090_1.webp",
                            IsActive = false,
                            Manufacturer = "ASG",
                            Name = "GL-06",
                            Price = 205.56m,
                            Quantity = 4,
                            Year = 2016
                        });
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Gunsmith", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Gunsmiths");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42794277-9c69-4699-999a-8c2e9ae4cdda"),
                            CategoryId = 4,
                            Description = "Fess 1-8x is a durable most attractive price-wise driven hunt scope with a variable magnification in the Buckler family that does an exceptional job at satisfying the needs of hunters, dynamic sports shooters and tactical shooters.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_Fess-II-1-8x24-Driven-Hunt-Scope-1152224248_1.webp",
                            IsActive = false,
                            Manufacturer = "Buckler",
                            Name = "Fess II 1-8x24 Driven Hunt Scope",
                            Price = 260.05m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("871cfa20-8398-4b87-80ed-ae1af711c1ce"),
                            CategoryId = 1,
                            Description = "A vertical forward grip made of metal intended for the attachment to KeyMod mounting system rails. Inside the mount is a small compartment for miscellaneous items. Features a rubber, anti-slip texture that improves the grip.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_KeyMod-Vertical-Grip-tan-1152221218_1.webp",
                            IsActive = false,
                            Manufacturer = "SHS",
                            Name = "KeyMod Vertical Grip",
                            Price = 23.65m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("ff7178e0-f91b-4a03-902f-c0b38f8daa5c"),
                            CategoryId = 1,
                            Description = "Shorter version of the angled front grip by PTS, made of a single piece of aluminum. Thanks to its compatibility with the M-LOK system, it can be mounted on any rail in this standard. Equipping the rifle with a front grip improves comfort and better control during fire.",
                            ImageUrl = "https://static4.gunfire.com/eng_pm_Fortis-Shift-TM-Short-Angle-Grip-Dark-Earth-1152230344_1.webp",
                            IsActive = false,
                            Manufacturer = "PTS",
                            Name = "Short Angle Grip",
                            Price = 50.50m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("65c6592d-08d9-4667-aac7-13d42693dbd0"),
                            CategoryId = 1,
                            Description = "A forward grip made of aluminum compatible with handguards featuring the KEYMOD mounting system.",
                            ImageUrl = "https://static3.gunfire.com/eng_pm_Aluminum-KeyMod-Angled-Forward-Grip-Black-1152227182_1.webp",
                            IsActive = false,
                            Manufacturer = "METAL",
                            Name = "Aluminum KeyMod Angled Forward Grip",
                            Price = 15.60m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("59ee3f74-b505-4071-8741-b48eb0790c4c"),
                            CategoryId = 1,
                            Description = "Theta Optics Red Dot 1x30 reflex sight is enclosed in a metal casing and powered by a CR2032 battery as well as allows to use a green or red dot during both day and night operations. The aimpoint can be smoothly regulated vertically and horizontally.",
                            ImageUrl = "https://static5.gunfire.com/eng_pm_Red-Dot-1x30-Reflex-Sight-Replica-Black-1152205530_1.webp",
                            IsActive = false,
                            Manufacturer = "THETA OPTICS",
                            Name = "Red Dot 1x30 Reflex Sight Replica",
                            Price = 26.50m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("bc726e85-3942-4eab-b84b-1bcb2cf8d538"),
                            CategoryId = 1,
                            Description = "A light, adjustable stock made of polymer, compatible with any replica equipped with an AR15 buffer tube.",
                            ImageUrl = "https://static1.gunfire.com/eng_pm_HM0321-Lightweight-Polymer-Stock-for-M4-M16-Replicas-Tan-1152227562_1.webp",
                            IsActive = false,
                            Manufacturer = "DOUBLE BELL",
                            Name = "HM0321 Lightweight Polymer Stock",
                            Price = 21.50m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("8b976634-c911-4046-b07b-a8e384637c71"),
                            CategoryId = 1,
                            Description = "Complete aluminum Hop-Up chamber and a precision 6,03mm stainless steel barrel made in CNC technology.",
                            ImageUrl = "https://static2.gunfire.com/eng_pm_Complete-Hop-Up-Chamber-with-6-03mm-370mm-S-Barrel-for-VFC-BCM-MCMR-Replicas-1152232630_1.webp",
                            IsActive = false,
                            Manufacturer = "TNT",
                            Name = "Complete Hop-Up Chamber with 6.03mm 370mm S+Barrel",
                            Price = 130m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("0cca6106-d2bc-40d6-8bbd-2ef74084eca4"),
                            CategoryId = 1,
                            Description = "This noise reduction is like nothing else. Really helpful on the battlefield and won't bother you, because it is really light.",
                            ImageUrl = "https://static1.gunfire.com/eng_pm_JG-MP5SD-Silencer-part-069-1152217123_1.webp",
                            IsActive = false,
                            Manufacturer = "JG WORKS",
                            Name = "JG MP5SD Silencer",
                            Price = 18.50m,
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c5e174e-3b0e-446f-86af-483d56fd7210"),
                            ConcurrencyStamp = "7d745425-08cf-4566-8c8f-76469c9f3dda",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8e445865-a24d-4543-a6c6-9443d048cdb9"),
                            RoleId = new Guid("2c5e174e-3b0e-446f-86af-483d56fd7210")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Cart", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.ApplicationUser", "Buyer")
                        .WithOne("Cart")
                        .HasForeignKey("AirsoftWebStore.Data.Models.Cart", "BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.CartItem", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirsoftWebStore.Data.Models.Consumative", "Consumative")
                        .WithMany("CartItems")
                        .HasForeignKey("ConsumativeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirsoftWebStore.Data.Models.Equipment", "Equipment")
                        .WithMany("CartItems")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirsoftWebStore.Data.Models.Gun", "Gun")
                        .WithMany("CartItems")
                        .HasForeignKey("GunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirsoftWebStore.Data.Models.Part", "Part")
                        .WithMany("CartItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cart");

                    b.Navigation("Consumative");

                    b.Navigation("Equipment");

                    b.Navigation("Gun");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Gun", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.Category", "Category")
                        .WithMany("Guns")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Gunsmith", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Part", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.Category", "Category")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirsoftWebStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AirsoftWebStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Cart");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Category", b =>
                {
                    b.Navigation("Guns");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Consumative", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Equipment", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Gun", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("AirsoftWebStore.Data.Models.Part", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
